services:
  registry:
    image: zeroc/icegridnode
    volumes:
      - type: bind
        read_only: false
        source: ./registry_store
        target: /var/lib/ice/icegrid
      - type: bind
        read_only: true
        source: ./config/registry.cfg
        target: /etc/icegridnode.conf
    networks:
      home-network:
        ipv4_address: 172.200.201.2

  jnode_home1:
    build:
      context: ./
      dockerfile: Dockerfile.node
      target: base
    depends_on:
      - "registry"
    volumes:
      - type: bind
        read_only: true
        source: ./server/build/libs/server.jar
        target: /ice/node/server.jar
      - type: bind
        read_only: true
        source: ./config
        target: /ice/node/config
      - type: bind
        read_only: true
        source: ./scripts
        target: /ice/node/scripts
      - type: bind
        read_only: false
        source: ./tmp
        target: /ice/node/data
    environment:
      - RUNNING_ENV=DOCKER
      - OBJECT_CONF_FILE=/ice/node/config/home1/objects.conf
    networks:
      - home-network
    entrypoint: ./scripts/wait-for-it.sh registry:4061 -- icegridnode --Ice.Config=config/home1/node.cfg

  jnode_garage:
    build:
      context: ./
      dockerfile: Dockerfile.node
      target: base
    depends_on:
      - "registry"
    volumes:
      - type: bind
        read_only: true
        source: ./server/build/libs/server.jar
        target: /ice/node/server.jar
      - type: bind
        read_only: true
        source: ./config
        target: /ice/node/config
      - type: bind
        read_only: true
        source: ./scripts
        target: /ice/node/scripts
      - type: bind
        read_only: false
        source: ./tmp
        target: /ice/node/data
    environment:
      - RUNNING_ENV=DOCKER
      - OBJECT_CONF_FILE=/ice/node/config/garage/objects.conf

    networks:
      - home-network
    entrypoint: ./scripts/wait-for-it.sh registry:4061 -- icegridnode --Ice.Config=config/garage/node.cfg

networks:
  home-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.201.0/24"
          gateway: "172.200.201.1"