services:
  registry:
    image: zeroc/icegridnode
    volumes:
      - type: bind
        read_only: false
        source: ./registry_store
        target: /var/lib/ice/icegrid
      - type: bind
        read_only: true
        source: ./registry.cfg
        target: /etc/icegridnode.conf
    networks:
      home-network:
        ipv4_address: 172.200.200.2

  jnode1:
    image: openjdk
    working_dir: /ice/node/
    depends_on:
      - "registry"
    volumes:
      - type: bind
        read_only: true
        source: ./server/build/libs/server.jar
        target: /ice/node/server.jar
      - type: bind
        read_only: true
        source: ./server.cfg
        target: /ice/node/server.cfg
      - type: bind
        read_only: true
        source: ./scripts/wait-for-it.sh
        target: /ice/node/wait-for-it.sh
    environment:
      - RUNNING_ENV=DOCKER
    networks:
      - home-network

    entrypoint: ./wait-for-it.sh registry:4061 -- java -jar server.jar --Ice.Config=server.cfg

networks:
  home-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.200.200.0/24"
          gateway: "172.200.200.1"